################################### English language #####################################
[en]
languageName = "En"
languageCode = "en-us"
contentDir = "content"
weight = 1
copyright = "Copyright Â© 2026 IB Sports Academy - All Rights Reserved."
# copyright = "Designed By [Themefisher](https://themefisher.com/) & Developed By [Gethugothemes](https://gethugothemes.com/)"

