############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = ""
weight = 1

[[main]]
name = "About"
weight = 2
hasChildren = true

  [[main]]
  parent = "About"
  name = "Our Story"
  url = "about/"
  weight = 1

  [[main]]
  parent = "About"
  name = "Ishwar Bhati"
  url = "about/ishwar-bhati/"
  weight = 2

  [[main]]
  parent = "About"
  name = "Meet The Team"
  url = "about/meet-the-team/"
  weight = 3

[[main]]
name = "Gallery"
url = "gallery/"
weight = 3

[[main]]
name = "Videos"
url = "videos/"
weight = 4

[[main]]
name = "Locations"
url = "locations/"
weight = 5

[[main]]
name = "Collaborate"
url = "collaborate/"
weight = 6

[[main]]
name = "Blog"
url = "https://blog.ibsportsacademy.com/"
weight = 7

[[main]]
weight = 8
name = "Pages"
hasChildren = true

  [[main]]
  parent = "Pages"
  name = "Privacy Policy"
  url = "privacy-policy/"
  weight = 1

  [[main]]
  parent = "Pages"
  name = "Terms & Conditions"
  url = "terms-and-conditions/"
  weight = 2

  [[main]]
  parent = "Pages"
  name = "Disclaimer"
  url = "disclaimer/"
  weight = 3

[[main]]
name = "Contact"
url = "contact/"
weight = 9


# footer menu
[[footer]]
name = "About"
url = "about/"
weight = 1

[[footer]]
name = "Blog"
url = "https://blog.ibsportsacademy.com/"
weight = 2

[[footer]]
name = "Partner With Us"
url = "collaborate/"
weight = 3

[[footer]]
name = "Privacy Policy"
url = "privacy-policy/"
weight = 4

[[footer]]
name = "Terms & Conditions"
url = "terms-and-conditions/"
weight = 5

[[footer]]
name = "Disclaimer"
url = "disclaimer/"
weight = 6
